### docker compose file for a mysql docker container ###
# 2 folders mounted:
# - one for the mysql data
# - one for possible startup scripts

version: "3"
services:
   mysql_db:
      container_name: mysql_db
      image: mysql:latest
      ports:
         - "3306:3306"
      restart: always
      volumes:
         - "./mysql_data:/var/lib/mysql"
         - "./startup_scripts:/docker-entrypoint-initdb.d"
      environment:
         - MYSQL_ROOT_PASSWORD=root

### end of file ###
