### author: Michael Wellner ###
### date: 23.10.2017 ###
### docker compose file for a mysql docker container ###

version: "3"

# service to build the docker image
services:
  mysql_db:
    container_name: mysql_db
    image: mysql/m1well:latest
    build: .
    ports:
      - "3306:3306"
    restart: always
    # volumes:
      # - mysql_data:/var/lib/mysql

# volumes:
  # mysql_data:

### end of file ###
