### author: Michael Wellner ###
### date: 23.10.2017 ###
### docker compose file for a postgres docker container ###

version: "3"

# service to build the docker image
services:
  postgres_db:
    container_name: postgres_db
    image: m1well/postgres_db:latest
    ports:
      - "5432:5432"
    volumes:
      - "./startup_scripts/:/docker-entrypoint-initdb.d/"
    restart: always

### end of file ###
