
### author: Michael Wellner ###
### date: 23.10.2017 ###
### docker compose file for an oracle docker container ###

version: "3"
services:
   oracle_db:
      container_name: oracle_db
      image: m1well/oracle_db:latest
      ports:
        - "49160:22"
        - "49161:1521"
        - "49162:8080"
      volumes:
        - "./startup_scripts/:/docker-entrypoint-initdb.d/"
      restart: always

### end of file ###
